[project]
name = "ctf-utils"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bidict>=0.23.1",
    "bitarray>=3.4.1",
    "cryptography>=44.0.2",
    "pygments>=2.19.1",
]
